(defparameter *dice* 0)
(defparameter *dice-rolls* 0)
(defparameter *one-pos* 7)
(defparameter *one-score* 0)
(defparameter *two-pos* 3)
(defparameter *two-score* 0)

(defun game-step ()
  (setf *one-pos* (mod (+ *one-pos* (+ *dice* 1) (+ *dice* 2) (+ *dice* 3)) 10))
  (incf *one-score* (1+ *one-pos*))
  (setf *dice* (mod (+ *dice* 3) 100))
  (incf *dice-rolls* 3)
  (if (>= *one-score* 1000)
      (return-from game-step))
  (setf *two-pos* (mod (+ *two-pos* (+ *dice* 1) (+ *dice* 2) (+ *dice* 3)) 10))
  (incf *two-score* (1+ *two-pos*))
  (setf *dice* (mod (+ *dice* 3) 100))
  (incf *dice-rolls* 3))

(do ((i 0 (1+ i)))
    ((or (>= *one-score* 1000) (>= *two-score* 1000)) NIL)
  (game-step)
  (format t "rolls: ~a, p1: (~a, ~a), p2: (~a, ~a)~%" *dice-rolls* *one-pos* *one-score* *two-pos* *two-score*))

(print *dice-rolls*)
(print (* *dice-rolls* (min *one-score* *two-score*)))
